version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "8000:8000"  # Fixed port mapping
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:mysecretpassword@db:5432/mydatabase
      CLAUDE_KEY: ${CLAUDE_KEY}
      PYTHONPATH: /app  # Ensure Python can find modules
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be ready
    env_file:
      - ./.env

volumes:
  db_data: